In [34]:
import numpy as np
import tensorflow as tf
import random
from collections import deque
import gym
import math

In [35]:
def softmax(x, scale = 1):
    x = np.array(x)/scale
    max_x = np.max(x)
    e_x = np.exp(x - max_x)
    p = e_x/e_x.sum()
    p = p/p.sum()

    return p

In [36]:
X = [[1, 2, 3]]
Y = [[1], [2], [3]]

sess = tf.Session()
Z = tf.matmul(X, Y)
sess.run(Z)
print (sess.run(Z))

W = Z + X - tf.reduce_mean(X,reduction_indices=1,keep_dims=True)
print (sess.run(W))

K = tf.reduce_mean(Y,reduction_indices=1,keep_dims=True)
print (sess.run(K))


for x in range(1, 3):
    print(x)

H = np.zeros([4, 3], dtype=np.uint8)
H[0, 0] = 1
H[0, 1] = 2
H[0, 2] = 3
H[1, 0] = 4
H[1, 1] = 5
H[1, 2] = 6
H[2, 0] = 7
H[2, 1] = 8
H[2, 2] = 9
H[3, 0] = 10
H[3, 1] = 11
H[3, 2] = 12

print(H[:, :2])
print( "--------------------------------")

TD = deque()

TD.append(3.2)
TD.append(4)
TD.append(5)

print(sum(TD))
print(TD[2])
print( "--------------------------------")

TD_norm_list = []
TD_error_list = [1.2, 2.8, 1.0]
TD_sum = sum(TD_error_list)
TD_norm_list = [TD_error_list[i] / TD_sum for i in range(3)]
print(TD_norm_list)

print( "--------------------------------")

TDT = np.zeros([len(TD_norm_list)])
print(TDT)
print(TDT[2])

TDT[1] = 0
if TDT[1] == 0:
    print("dd")

print( "--------------------------------")

TDDD = [1, 2, 3]
WDDD = [np.power((10 * TDDD[i]), -0.5) for i in range(3)]
print(TDDD)
print(WDDD)

maxW = np.max(WDDD)
WDDD = [WDDD[i] / maxW for i in range(3)]
print(WDDD)

#loss = tf.reduce_sum(tf.multiply(WIS, WDDD))
#print(loss)

print( "--------------------------------")
Y = tf.placeholder(shape=[1, 3], dtype=tf.float32)
WIS = tf.placeholder(shape=[1, 1], dtype=tf.float32)

print(Y)
#loss = tf.multiply(WIS, Y)
loss = WIS * Y
print(loss)

print( "--------------------------------")

TDDD = [1, 4, 3]
print(len(TDDD))
TDDD = np.sort(TDDD)[::-1]
print(TDDD[0:2].sum())
TDDD = softmax(TDDD)
print(TDDD)
print(TDDD.sum())
#TDDD = np.cumsum(TDDD)
#print(TDDD)

print( "--------------------------------")
#print(np.log(10))
seed_1 = 3
np.random.seed(seed_1)
print(np.random.choice(len(TDDD),size=1,p=TDDD))
#np.random.seed(seed_1)
print(np.random.choice(len(TDDD),size=1,p=TDDD))
#np.random.seed(seed_1)
print(np.random.choice(len(TDDD),size=1,p=TDDD))
#np.random.seed(seed_1)
print(np.random.choice(len(TDDD),size=1,p=TDDD))
np.random.seed(seed_1)
print(np.random.choice(len(TDDD),size=1,p=TDDD))
#np.random.seed(seed_1)
print(np.random.choice(len(TDDD),size=1,p=TDDD))
#np.random.seed(seed_1)
print(np.random.choice(len(TDDD),size=1,p=TDDD))
#np.random.seed(seed_1)
print(np.random.choice(len(TDDD),size=1,p=TDDD))


[[14]]
[[13 14 15]]
[[1]
 [2]
 [3]]
1
2
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
--------------------------------
12.2
5
--------------------------------
[0.24, 0.5599999999999999, 0.2]
--------------------------------
[0. 0. 0.]
0.0
dd
--------------------------------
[1, 2, 3]
[0.31622776601683794, 0.22360679774997896, 0.18257418583505536]
[1.0, 0.7071067811865475, 0.5773502691896257]
--------------------------------
Tensor("Placeholder_22:0", shape=(1, 3), dtype=float32)
Tensor("mul_11:0", shape=(1, 3), dtype=float32)
--------------------------------
3
7
[0.70538451 0.25949646 0.03511903]
1.0
--------------------------------
[0]
[1]
[0]
[0]
[0]
[1]
[0]
[0]
